const express = require('express');
const router = express.Router();
const gpsRoutes = require('./api/routes/gps');
const userRoutes = require('./api/routes/user');
const trackerListRoutes = require('./api/routes/trackerList');
const trackerRoutes = require('./api/routes/tracker');
router.use('/tracker',trackerRoutes);
router.use('/users',userRoutes);
router.use('/trackerList',trackerListRoutes);
module.exports = router;