const express = require('express');
const router = express.Router();
const gpsRoutes = require('./api/routes/gps');
const userRoutes = require('./api/routes/user');
const trackerListRoutes = require('./api/routes/trackerList');
const trackerRoutes = require('./api/routes/tracker');
const busListRoutes = require('./api/routes/busList');
const routeListRoutes = require('./api/routes/routeList');
router.use('/tracker',trackerRoutes);
router.use('/users',userRoutes);
router.use('/trackerList',trackerListRoutes);
router.use('/routeList',routeListRoutes);
router.use('/busList',busListRoutes);
module.exports = router;